export enum Genre {
    Adventure = 0,
    Action = 1,
     Comedy = 2,
     SciFi = 3,
     Romance = 4,
     Fantasy = 5,
     Horror = 6,
     Thriller = 7,
     Western = 8,
     Documentary = 9
    // Action = 0,
    // Adventure = 1,
    // Comedy = 2,
    // Documentary = 3,
    // SciFi = 4,
    // Romance = 5,
    // Fantasy = 6,
    // Horror = 7,
    // Thriller = 8,
    // Western = 9,
 }
